=== AGLEnergy/arc/src/main/resources/metadata-schema.json
{
    "definitions": {},
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://example.com/example.json",
    "items": {
        "$id": "http://example.com/example.json/items",
        "type": "object",
        "properties": {
            "id": {
                "$id": "http://example.com/example.json/items/properties/id",
                "type": "string",
                "title": "id",
                "description": "Field unique identifier (GUID).",
                "default": "",
                "examples": [
                    "8275594c-6177-475e-b462-5f15d015df7c"
                ]
            },
            "name": {
                "$id": "http://example.com/example.json/items/properties/name",
                "type": "string",
                "title": "name",
                "description": "The name of the field.",
                "default": "",
                "examples": [
                    "first_name",
                    "last_name"
                ]
            },
            "description": {
                "$id": "http://example.com/example.json/items/properties/description",
                "type": "string",
                "title": "description",
                "description": "A description of the what the field represents.",
                "default": "",
                "examples": [
                    "Customer First Name",
                    "Timestamp of last customer interaction."
                ]
            },
            "nullReplacementValue": {
                "$id": "http://example.com/example.json/items/properties/nullReplacementValue",
                "type": "string",
                "title": "nullReplacementValue",
                "description": "The value to replace any nulls with.",
                "default": "",
                "examples": [
                    "true"
                ]
            },
            "trim": {
                "$id": "http://example.com/example.json/items/properties/trim",
                "type": "boolean",
                "title": "trim",
                "description": "Whether to trim this field before attempting data type conversion.",
                "default": false,
                "examples": [
                    true,
                    false
                ]
            },
            "nullable": {
                "$id": "http://example.com/example.json/items/properties/nullable",
                "type": "boolean",
                "title": "nullable",
                "description": "Whether this field is allowed to be null.",
                "default": false,
                "examples": [
                    true,
                    false
                ]
            },
            "nullableValues": {
                "$id": "http://example.com/example.json/items/properties/nullableValues",
                "type": "array",
                "title": "nullableValues",
                "description": "A list of values which will be treated as valid null values.",
                "examples": [
                    "NULL",
                    "null",
                    ""
                ],
                "items": {
                    "$id": "http://example.com/example.json/items/properties/nullableValues/items",
                    "type": "string",
                    "title": "The 0 Schema.",
                    "description": "An explanation about the purpose of this instance.",
                    "default": "",
                    "examples": [
                        ""
                    ]
                }
            },
            "primaryKey": {
                "$id": "http://example.com/example.json/items/properties/primaryKey",
                "type": "boolean",
                "title": "primaryKey",
                "description": "A flag to indicate if this is a primary key for metadata tracking/validation purposes.",
                "default": false,
                "examples": [
                    true,
                    false
                ]
            },
            "type": {
                "$id": "http://example.com/example.json/items/properties/type",
                "type": "string",
                "enum": [
                    "date",
                    "decimal",
                    "integer",
                    "string",
                    "timestamp",
                    "boolean"
                ],
                "title": "type",
                "description": "The data type of this field.",
                "default": "",
                "examples": [
                    "date",
                    "decimal",
                    "integer",
                    "string",
                    "timestamp"
                ]
            },
            "length": {
                "$id": "http://example.com/example.json/items/properties/length",
                "type": "integer",
                "title": "length",
                "description": "The length of the field for metadata tracking/validation purposes.",
                "examples": [
                    6,
                    255
                ]
            },
            "precision": {
                "$id": "http://example.com/example.json/items/properties/precision",
                "type": "integer",
                "title": "precision",
                "description": "Precision of Decimal field. For example, the number 1234.567 has a precision of seven.",
                "minimum": 1,
                "examples": [
                    7
                ]
            },
            "scale": {
                "$id": "http://example.com/example.json/items/properties/scale",
                "type": "integer",
                "title": "scale",
                "description": "Scale of Decimal field. For example, the number 1234.567 has a scale of three.",
                "minimum": 0,
                "examples": [
                    3
                ]
            },
            "timezoneId": {
                "$id": "http://example.com/example.json/items/properties/timezoneId",
                "type": "string",
                "title": "timezoneId",
                "description": "The timezone (offset) used to parse timestamp.",
                "examples": [
                    "+1000",
                    "AEST",
                    "Sydney/Australia"
                ]
            },
            "formatters": {
                "$id": "http://example.com/example.json/items/properties/formatters",
                "type": "array",
                "title": "formatters",
                "description": "A list of formatters to attempt to convert a string to a timestamp. Order by most frequent value descending.",
                "examples": [
                    "dd/MM/yyyy HH:mm:ss",
                    "dd/MM/yyyy H:mm:ss",
                    "dd/MM/yyyy HH:mm",
                    "dd/MM/yyyy H:mm",
                    "d/MM/yyyy HH:mm:ss",
                    "d/MM/yyyy H:mm:ss",
                    "d/MM/yyyy HH:mm",
                    "d/MM/yyyy H:mm"
                ]
            },
            "table": {
                "$id": "http://example.com/example.json/items/properties/table",
                "type": "string",
                "title": "table",
                "description": "A source table name used for metadata tracking/validation purposes.",
                "default": "",
                "examples": [
                    "customer_details",
                    "transactions"
                ]
            },
            "trueValues": {
                "$id": "http://example.com/example.json/items/properties/trueValues",
                "type": "array",
                "title": "trueValues",
                "description": "A list of values which are considered as true. Try to order this list so the values are arranged from most frequent to least frequent.",
                "examples": [
                    "true",
                    "T",
                    "1"
                ]
            },
            "falseValues": {
                "$id": "http://example.com/example.json/items/properties/falseValues",
                "type": "array",
                "title": "falseValues",
                "description": "A list of values which are considered as false. Try to order this list so the values are arranged from most frequent to least frequent.",
                "examples": [
                    "false",
                    "F",
                    "0"
                ]
            },
            "metadata": {
                "$id": "http://example.com/example.json/items/properties/metadata",
                "type": "object",
                "title": "metadata",
                "description": "Any metadata to attach to the column."
            }
        },
        "allOf": [
            {
                "if": {
                    "properties": {
                        "type": {
                            "enum": [
                                "integer",
                                "long",
                                "string"
                            ]
                        }
                    }
                },
                "then": {
                    "required": [
                        "id",
                        "name",
                        "trim",
                        "nullable",
                        "type",
                        "nullableValues"
                    ]
                }
            },
            {
                "if": {
                    "properties": {
                        "type": {
                            "enum": [
                                "decimal"
                            ]
                        }
                    }
                },
                "then": {
                    "required": [
                        "id",
                        "name",
                        "trim",
                        "nullable",
                        "type",
                        "nullableValues",
                        "precision",
                        "scale"
                    ]
                }
            },
            {
                "if": {
                    "properties": {
                        "type": {
                            "enum": [
                                "timestamp"
                            ]
                        }
                    }
                },
                "then": {
                    "required": [
                        "id",
                        "name",
                        "trim",
                        "nullable",
                        "type",
                        "nullableValues",
                        "timezoneId",
                        "formatters"
                    ]
                }
            },
            {
                "if": {
                    "properties": {
                        "type": {
                            "enum": [
                                "date"
                            ]
                        }
                    }
                },
                "then": {
                    "required": [
                        "id",
                        "name",
                        "trim",
                        "nullable",
                        "type",
                        "nullableValues",
                        "formatters"
                    ]
                }
            },
            {
                "if": {
                    "properties": {
                        "type": {
                            "enum": [
                                "time"
                            ]
                        }
                    }
                },
                "then": {
                    "required": [
                        "id",
                        "name",
                        "trim",
                        "nullable",
                        "type",
                        "nullableValues",
                        "formatters"
                    ]
                }
            },
            {
                "if": {
                    "properties": {
                        "type": {
                            "enum": [
                                "boolean"
                            ]
                        }
                    }
                },
                "then": {
                    "required": [
                        "id",
                        "name",
                        "trim",
                        "nullable",
                        "type",
                        "nullableValues",
                        "trueValues",
                        "falseValues"
                    ]
                }
            }
        ],
        "additionalProperties": false
    }
}

=== AGLEnergy/arc/tutorial/gnaf/meta/0/locality.json
[{
  "id" : "5b9cbc7d-40c2-45fa-a7a7-abbf539205a0",
  "name" : "locality_pid",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "a583265a-b718-4fcf-a43d-4dbeaefc0e01",
  "name" : "date_created",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "date",
  "formatters" : [ "uuuu-MM-dd" ]
},{
  "id" : "322c014c-2dec-42eb-b37b-ee3536c60526",
  "name" : "date_retired",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "date",
  "formatters" : [ "uuuu-MM-dd" ]
},{
  "id" : "0ac3ba37-65a3-4630-928b-5ffbd268194e",
  "name" : "locality_name",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "1ce4b78e-cd4a-461b-80d3-ea2abe81cd8d",
  "name" : "primary_postcode",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "ae1010e2-0109-475c-a794-96b1d2428081",
  "name" : "locality_class_code",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "89ecb919-54b4-4727-9028-0670720bc9f2",
  "name" : "state_pid",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "c2e54026-f53e-440f-b2ed-504345a9b6ad",
  "name" : "gnaf_locality_pid",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "815b2b54-57e8-4909-80db-684cb15563e0",
  "name" : "gnaf_reliability_code",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "integer"
}]

=== AGLEnergy/arc/tutorial/gnaf/meta/0/street_locality_point.json
[{
  "id" : "0cbfa468-c098-42db-9893-3b1b38854517",
  "name" : "street_locality_point_pid",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "b6c45d86-08e0-449b-a115-3f5a99c8fe0f",
  "name" : "date_created",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "date",
  "formatters" : [ "yyyy-MM-dd" ]
},{
  "id" : "be925693-6a9e-4f4b-9e3b-5237e5fb28d2",
  "name" : "date_retired",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "date",
  "formatters" : [ "yyyy-MM-dd" ]
},{
  "id" : "86387efd-fb9f-45c9-a5a3-5b5762414fce",
  "name" : "street_locality_pid",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "d8bd9acb-8f32-4592-9871-c4f01d385c68",
  "name" : "boundary_extent",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "integer"
},{
  "id" : "bf1812f3-e368-4d8c-97a7-9c3d263cd82d",
  "name" : "planimetric_accuracy",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "long"
},{
  "id" : "0903d218-f670-4d31-822c-fc7782f2d8d8",
  "name" : "longitude",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "decimal",
  "precision" : 11,
  "scale" : 8
},{
  "id" : "77c5b866-58d6-4904-8ba2-56c58d68cd2a",
  "name" : "latitude",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "decimal",
  "precision" : 10,
  "scale" : 8
}]

=== AGLEnergy/arc/tutorial/gnaf/meta/0/level_type_aut.json
[{
  "id" : "ec603d1d-2f5d-47ac-a128-b0ae6257c648",
  "name" : "code",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "3467bcaa-f926-418c-b0bb-71023a5f8194",
  "name" : "name",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "851b8f6e-6e55-4b71-aae1-c5a7bc352949",
  "name" : "description",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
}]

=== AGLEnergy/arc/tutorial/gnaf/meta/0/locality_class_aut.json
[{
  "id" : "84133ae7-15cb-4dd4-b0e7-13b0413a4efe",
  "name" : "code",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "920a8185-b07c-46ce-8c2f-a049c807dcac",
  "name" : "name",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "008fb619-bdcc-4aa0-82c4-219dfc43a9c8",
  "name" : "description",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
}]

=== AGLEnergy/arc/tutorial/gnaf/meta/0/ps_join_type_aut.json
[{
  "id" : "c7211b05-d99a-4774-a6b9-754553877e7f",
  "name" : "code",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "integer"
},{
  "id" : "6a4a1dd7-e748-400b-a958-6863a99f75bb",
  "name" : "name",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "cbfbf2fa-c94a-487d-8f4b-19e972f0a152",
  "name" : "description",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
}]

=== AGLEnergy/arc/tutorial/gnaf/meta/0/locality_neighbour.json
[{
  "id" : "0ae62bac-871e-4350-bec5-b7e1297a5eba",
  "name" : "locality_neighbour_pid",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "f0c2dba3-3a99-4436-937c-49fb9fa334bc",
  "name" : "date_created",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "date",
  "formatters" : [ "uuuu-MM-dd" ]
},{
  "id" : "6049a113-d28f-49fd-826b-6d3adcc663e7",
  "name" : "date_retired",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "date",
  "formatters" : [ "uuuu-MM-dd" ]
},{
  "id" : "1425bba7-e271-4548-90f4-8c51fddd60ed",
  "name" : "locality_pid",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "af6deaf2-22e9-43c3-b5c5-e5a5af9d91d0",
  "name" : "neighbour_locality_pid",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
}]

=== AGLEnergy/arc/tutorial/streaming/job/0/fake_data_meta.json
[
  {
    "id": "1cdf4091-d5a5-4abf-b48a-1ad8fe2be4de",
    "name": "customer_id",
    "description": "The customer identifier.",
    "trim": true,
    "nullable": true,
    "primaryKey": false,
    "type": "integer",
    "nullableValues": [
      "",
      "null"
    ]
  },
  {
    "id": "97d8f4e1-b87f-468a-a99c-40b8af36eebf",
    "name": "account_id",
    "description": "The account identifier.",
    "trim": true,
    "nullable": true,
    "primaryKey": false,
    "type": "integer",
    "nullableValues": [
      "",
      "null"
    ]
  },
  {
    "id": "f457e562-5c7a-4215-a754-ab749509f3fb",
    "name": "balance",
    "description": "The account balance.",
    "trim": true,
    "nullable": true,
    "primaryKey": false,
    "type": "decimal",
    "nullableValues": [
      "",
      "null"
    ],
    "precision": 10,
    "scale": 2
  },
  {
    "id": "8d3c9cb7-7179-4a8f-824d-7d2f41fd3d07",
    "name": "credit_score",
    "description": "The customer credit score.",
    "trim": true,
    "nullable": true,
    "primaryKey": false,
    "type": "integer",
    "nullableValues": [
      "",
      "null"
    ]
  }
]

=== AGLEnergy/arc/tutorial/gnaf/meta/0/locality_alias.json
[{
  "id" : "7daa7284-d7d4-4e7a-8506-94604848da1f",
  "name" : "locality_alias_pid",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "abfa58fa-6597-4b79-bb75-912392b34880",
  "name" : "date_created",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "date",
  "formatters" : [ "yyyy-MM-dd" ]
},{
  "id" : "527741ae-2228-4f44-97db-b09dfe7ab3bb",
  "name" : "date_retired",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "date",
  "formatters" : [ "yyyy-MM-dd" ]
},{
  "id" : "780bdd13-a083-44cf-bf12-a6ed21805c1c",
  "name" : "locality_pid",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "dc95d051-56d5-4a50-9845-f54fb9230ddf",
  "name" : "name",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "032cc08e-fc7f-4d7f-9b16-5b5ce94b8e51",
  "name" : "postcode",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "c6b5ef63-8695-4080-b39e-b7b8350b6c60",
  "name" : "alias_type_code",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "0fc0b976-5696-4722-ae7a-f1e4e1dcde34",
  "name" : "state_pid",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
}]
