=== AGLEnergy/arc/src/main/resources/metadata-schema.json
{
    "definitions": {},
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://example.com/example.json",
    "items": {
        "$id": "http://example.com/example.json/items",
        "type": "object",
        "properties": {
            "id": {
                "$id": "http://example.com/example.json/items/properties/id",
                "type": "string",
                "title": "id",
                "description": "Field unique identifier (GUID).",
                "default": "",
                "examples": [
                    "8275594c-6177-475e-b462-5f15d015df7c"
                ]
            },
            "name": {
                "$id": "http://example.com/example.json/items/properties/name",
                "type": "string",
                "title": "name",
                "description": "The name of the field.",
                "default": "",
                "examples": [
                    "first_name",
                    "last_name"
                ]
            },
            "description": {
                "$id": "http://example.com/example.json/items/properties/description",
                "type": "string",
                "title": "description",
                "description": "A description of the what the field represents.",
                "default": "",
                "examples": [
                    "Customer First Name",
                    "Timestamp of last customer interaction."
                ]
            },
            "nullReplacementValue": {
                "$id": "http://example.com/example.json/items/properties/nullReplacementValue",
                "type": "string",
                "title": "nullReplacementValue",
                "description": "The value to replace any nulls with.",
                "default": "",
                "examples": [
                    "true"
                ]
            },
            "trim": {
                "$id": "http://example.com/example.json/items/properties/trim",
                "type": "boolean",
                "title": "trim",
                "description": "Whether to trim this field before attempting data type conversion.",
                "default": false,
                "examples": [
                    true,
                    false
                ]
            },
            "nullable": {
                "$id": "http://example.com/example.json/items/properties/nullable",
                "type": "boolean",
                "title": "nullable",
                "description": "Whether this field is allowed to be null.",
                "default": false,
                "examples": [
                    true,
                    false
                ]
            },
            "nullableValues": {
                "$id": "http://example.com/example.json/items/properties/nullableValues",
                "type": "array",
                "title": "nullableValues",
                "description": "A list of values which will be treated as valid null values.",
                "examples": [
                    "NULL",
                    "null",
                    ""
                ],
                "items": {
                    "$id": "http://example.com/example.json/items/properties/nullableValues/items",
                    "type": "string",
                    "title": "The 0 Schema.",
                    "description": "An explanation about the purpose of this instance.",
                    "default": "",
                    "examples": [
                        ""
                    ]
                }
            },
            "primaryKey": {
                "$id": "http://example.com/example.json/items/properties/primaryKey",
                "type": "boolean",
                "title": "primaryKey",
                "description": "A flag to indicate if this is a primary key for metadata tracking/validation purposes.",
                "default": false,
                "examples": [
                    true,
                    false
                ]
            },
            "type": {
                "$id": "http://example.com/example.json/items/properties/type",
                "type": "string",
                "enum": [
                    "date",
                    "decimal",
                    "integer",
                    "string",
                    "timestamp",
                    "boolean"
                ],
                "title": "type",
                "description": "The data type of this field.",
                "default": "",
                "examples": [
                    "date",
                    "decimal",
                    "integer",
                    "string",
                    "timestamp"
                ]
            },
            "length": {
                "$id": "http://example.com/example.json/items/properties/length",
                "type": "integer",
                "title": "length",
                "description": "The length of the field for metadata tracking/validation purposes.",
                "examples": [
                    6,
                    255
                ]
            },
            "precision": {
                "$id": "http://example.com/example.json/items/properties/precision",
                "type": "integer",
                "title": "precision",
                "description": "Precision of Decimal field. For example, the number 1234.567 has a precision of seven.",
                "minimum": 1,
                "examples": [
                    7
                ]
            },
            "scale": {
                "$id": "http://example.com/example.json/items/properties/scale",
                "type": "integer",
                "title": "scale",
                "description": "Scale of Decimal field. For example, the number 1234.567 has a scale of three.",
                "minimum": 0,
                "examples": [
                    3
                ]
            },
            "timezoneId": {
                "$id": "http://example.com/example.json/items/properties/timezoneId",
                "type": "string",
                "title": "timezoneId",
                "description": "The timezone (offset) used to parse timestamp.",
                "examples": [
                    "+1000",
                    "AEST",
                    "Sydney/Australia"
                ]
            },
            "formatters": {
                "$id": "http://example.com/example.json/items/properties/formatters",
                "type": "array",
                "title": "formatters",
                "description": "A list of formatters to attempt to convert a string to a timestamp. Order by most frequent value descending.",
                "examples": [
                    "dd/MM/yyyy HH:mm:ss",
                    "dd/MM/yyyy H:mm:ss",
                    "dd/MM/yyyy HH:mm",
                    "dd/MM/yyyy H:mm",
                    "d/MM/yyyy HH:mm:ss",
                    "d/MM/yyyy H:mm:ss",
                    "d/MM/yyyy HH:mm",
                    "d/MM/yyyy H:mm"
                ]
            },
            "table": {
                "$id": "http://example.com/example.json/items/properties/table",
                "type": "string",
                "title": "table",
                "description": "A source table name used for metadata tracking/validation purposes.",
                "default": "",
                "examples": [
                    "customer_details",
                    "transactions"
                ]
            },
            "trueValues": {
                "$id": "http://example.com/example.json/items/properties/trueValues",
                "type": "array",
                "title": "trueValues",
                "description": "A list of values which are considered as true. Try to order this list so the values are arranged from most frequent to least frequent.",
                "examples": [
                    "true",
                    "T",
                    "1"
                ]
            },
            "falseValues": {
                "$id": "http://example.com/example.json/items/properties/falseValues",
                "type": "array",
                "title": "falseValues",
                "description": "A list of values which are considered as false. Try to order this list so the values are arranged from most frequent to least frequent.",
                "examples": [
                    "false",
                    "F",
                    "0"
                ]
            },
            "metadata": {
                "$id": "http://example.com/example.json/items/properties/metadata",
                "type": "object",
                "title": "metadata",
                "description": "Any metadata to attach to the column."
            }
        },
        "allOf": [
            {
                "if": {
                    "properties": {
                        "type": {
                            "enum": [
                                "integer",
                                "long",
                                "string"
                            ]
                        }
                    }
                },
                "then": {
                    "required": [
                        "id",
                        "name",
                        "trim",
                        "nullable",
                        "type",
                        "nullableValues"
                    ]
                }
            },
            {
                "if": {
                    "properties": {
                        "type": {
                            "enum": [
                                "decimal"
                            ]
                        }
                    }
                },
                "then": {
                    "required": [
                        "id",
                        "name",
                        "trim",
                        "nullable",
                        "type",
                        "nullableValues",
                        "precision",
                        "scale"
                    ]
                }
            },
            {
                "if": {
                    "properties": {
                        "type": {
                            "enum": [
                                "timestamp"
                            ]
                        }
                    }
                },
                "then": {
                    "required": [
                        "id",
                        "name",
                        "trim",
                        "nullable",
                        "type",
                        "nullableValues",
                        "timezoneId",
                        "formatters"
                    ]
                }
            },
            {
                "if": {
                    "properties": {
                        "type": {
                            "enum": [
                                "date"
                            ]
                        }
                    }
                },
                "then": {
                    "required": [
                        "id",
                        "name",
                        "trim",
                        "nullable",
                        "type",
                        "nullableValues",
                        "formatters"
                    ]
                }
            },
            {
                "if": {
                    "properties": {
                        "type": {
                            "enum": [
                                "time"
                            ]
                        }
                    }
                },
                "then": {
                    "required": [
                        "id",
                        "name",
                        "trim",
                        "nullable",
                        "type",
                        "nullableValues",
                        "formatters"
                    ]
                }
            },
            {
                "if": {
                    "properties": {
                        "type": {
                            "enum": [
                                "boolean"
                            ]
                        }
                    }
                },
                "then": {
                    "required": [
                        "id",
                        "name",
                        "trim",
                        "nullable",
                        "type",
                        "nullableValues",
                        "trueValues",
                        "falseValues"
                    ]
                }
            }
        ],
        "additionalProperties": false
    }
}

=== AGLEnergy/arc/tutorial/gnaf/meta/0/geocode_reliability_aut.json
[{
  "id" : "5e052ef9-91c8-4378-853b-7ab0cc5a4d25",
  "name" : "code",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "integer"
},{
  "id" : "2dc097b3-eec7-4c22-85ca-31859a197759",
  "name" : "name",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "5e7967a7-5285-48d1-90da-ad70a135dbf8",
  "name" : "description",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
}]

=== AGLEnergy/arc/tutorial/gnaf/meta/0/mb_2016.json
[{
  "id" : "470b2532-beeb-4865-b19f-ae0e9ecc544d",
  "name" : "mb_2016_pid",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "7d3279fc-ccc1-4141-a763-ef3eca047f27",
  "name" : "date_created",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "date",
  "formatters" : [ "uuuu-MM-dd" ]
},{
  "id" : "d52df66e-4e88-46ef-b1ae-446c97676cfd",
  "name" : "date_retired",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "date",
  "formatters" : [ "uuuu-MM-dd" ]
},{
  "id" : "6aa8f7a4-1bc4-438e-91b2-91ec383fb764",
  "name" : "mb_2016_code",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
}]

=== AGLEnergy/arc/tutorial/gnaf/meta/0/address_detail.json
[{
  "id" : "e893d003-2c47-48ba-b5e8-4d51a5bb9351",
  "name" : "address_detail_pid",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "67040349-2393-4529-a8a2-1b5fdfc0ca1b",
  "name" : "date_created",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "date",
  "formatters" : [ "yyyy-MM-dd" ]
},{
  "id" : "565c8fd5-80ec-48f8-b578-e84b162b838d",
  "name" : "date_last_modified",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "date",
  "formatters" : [ "yyyy-MM-dd" ]
},{
  "id" : "79796069-b47c-4df4-8d4d-79a62d5b2737",
  "name" : "date_retired",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "date",
  "formatters" : [ "yyyy-MM-dd" ]
},{
  "id" : "04a2026e-4105-4413-9cff-7f4705213a5d",
  "name" : "building_name",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "f9f58f10-c1d5-4684-9ca7-ed2ab1143aad",
  "name" : "lot_number_prefix",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "f56c2451-c0ed-4acb-a3f3-b38472582d04",
  "name" : "lot_number",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "249b6931-f6cd-485a-97f7-fac9a9f5fc21",
  "name" : "lot_number_suffix",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "f4502387-be2d-424d-bf13-0566aebd35f3",
  "name" : "flat_type_code",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "31c2cb77-9326-4a63-9e70-3c1dc0fe70b3",
  "name" : "flat_number_prefix",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "72e2f4b5-8014-46fd-910d-370408be5a6a",
  "name" : "flat_number",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "integer"
},{
  "id" : "1fb00e20-8589-4918-b2a9-7756589e7ba7",
  "name" : "flat_number_suffix",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "d426af0f-c8ec-4c99-a62a-b76aa5742afc",
  "name" : "level_type_code",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "b5d2158c-9506-4ddc-bd26-2a83bf32bbed",
  "name" : "level_number_prefix",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "5d5460a3-1725-4600-b8f9-7f7cda06d830",
  "name" : "level_number",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "integer"
},{
  "id" : "d5081543-e940-4802-b2f6-47ab19828202",
  "name" : "level_number_suffix",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "4ea95241-af76-4531-ae96-a75b72aedef3",
  "name" : "number_first_prefix",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "97a6a231-52cf-4687-b445-a73eb9cca6ff",
  "name" : "number_first",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "integer"
},{
  "id" : "65b9f88e-951f-4175-b717-1914d887291c",
  "name" : "number_first_suffix",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "ade60691-66de-4202-b7ce-c68d7a201331",
  "name" : "number_last_prefix",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "4f213e5b-ce32-438f-b8bc-9c828da2b3f2",
  "name" : "number_last",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "integer"
},{
  "id" : "1915d454-c573-44f3-b94c-847b12f27319",
  "name" : "number_last_suffix",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "fa3ae0ae-fb1a-4be7-9c12-09d144cc86a0",
  "name" : "street_locality_pid",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "e67725a4-6802-4b53-8d2a-6b91e9265ab9",
  "name" : "location_description",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "6484dbd1-1a63-47fe-bd0c-41242dcddc7f",
  "name" : "locality_pid",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "ca44f1ae-7e6e-4984-b6b8-98777b2ed549",
  "name" : "alias_principal",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "3ca66458-4ac2-4fdd-9c35-7630eeae0b52",
  "name" : "postcode",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "6609f530-f7ae-486a-9924-a3c39f04ba6a",
  "name" : "private_street",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "69535c8e-b684-4ab5-9d52-d33c9b4b8b63",
  "name" : "legal_parcel_id",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "d14bde43-ced5-410b-be16-9b6f29e920ea",
  "name" : "confidence",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "integer"
},{
  "id" : "e85e65f2-298e-44cd-a566-73df24259be1",
  "name" : "address_site_pid",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "d6576cdb-f415-41b6-b891-c37df05bfb36",
  "name" : "level_geocoded_code",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "integer"
},{
  "id" : "fc453e76-a206-4135-a942-41bdb99244f1",
  "name" : "property_pid",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "3b2fea9f-2a52-4fd5-b3b3-61657dd11533",
  "name" : "gnaf_property_pid",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "e09c6d40-cc03-4a34-8180-ce1259da9a54",
  "name" : "primary_secondary",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
}]

=== AGLEnergy/arc/tutorial/gnaf/meta/0/address_site.json
[{
  "id" : "8f6403fd-f687-4265-9303-b2c92a7625b5",
  "name" : "address_site_pid",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "61af1fd2-4466-4a67-9bcf-a7ce6d683e4b",
  "name" : "date_created",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "date",
  "formatters" : [ "yyyy-MM-dd" ]
},{
  "id" : "92267f85-b86b-4f8e-8f20-ae4a57c80a97",
  "name" : "date_retired",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "date",
  "formatters" : [ "yyyy-MM-dd" ]
},{
  "id" : "61f55f99-9bf1-42c3-a46e-a6b599aedc50",
  "name" : "address_type",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "7288906e-065e-4906-b0c0-a6d6b3de19f9",
  "name" : "address_site_name",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
}]

=== AGLEnergy/arc/tutorial/gnaf/meta/0/primary_secondary.json
[{
  "id" : "fb447522-478e-4925-9e13-a075fe426c3b",
  "name" : "primary_secondary_pid",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "f62bc291-35b6-4441-8251-e2c3a2fd2047",
  "name" : "primary_pid",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "1d1b8e5b-96d3-4814-9e69-921513a892da",
  "name" : "secondary_pid",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "915308ce-22c1-4194-aca1-775b2b9a3586",
  "name" : "date_created",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "date",
  "formatters" : [ "yyyy-MM-dd" ]
},{
  "id" : "6efe0c38-da05-46c1-bae8-dd28006c7dad",
  "name" : "date_retired",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "date",
  "formatters" : [ "yyyy-MM-dd" ]
},{
  "id" : "6cb19e74-0de8-459a-b233-afa68b66444f",
  "name" : "ps_join_type_code",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "integer"
},{
  "id" : "9f1bc012-7cee-4dc1-8e0f-04a67cff8801",
  "name" : "ps_join_comment",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
}]

=== AGLEnergy/arc/tutorial/gnaf/meta/0/address_default_geocode.json
[{
  "id" : "c6f8f048-7d3a-4faa-8270-a22d9affe91e",
  "name" : "address_default_geocode_pid",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "978da0c8-2fb6-4f75-a359-179b3b8b39f1",
  "name" : "date_created",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "date",
  "formatters" : [ "yyyy-MM-dd" ]
},{
  "id" : "000a2ec4-5ce7-44f9-9eed-0af9f4433ce8",
  "name" : "date_retired",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "date",
  "formatters" : [ "yyyy-MM-dd" ]
},{
  "id" : "bd55eb85-6e8b-4597-8126-efd5cebc11cd",
  "name" : "address_detail_pid",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "c68d4d2f-2874-459d-8832-903ee52a22fd",
  "name" : "geocode_type_code",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "e1cb660b-d5ad-4ae4-98ec-83836d66603b",
  "name" : "longitude",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "decimal",
  "precision" : 11,
  "scale" : 8
},{
  "id" : "8aef8da0-6f82-4413-8ded-12fbd159bb2e",
  "name" : "latitude",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "decimal",
  "precision" : 10,
  "scale" : 8
}]

=== AGLEnergy/arc/tutorial/gnaf/meta/0/state.json
[{
  "id" : "e3aca0aa-2172-44a0-8c5e-6e6f99b1f066",
  "name" : "state_pid",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "d86e6dbd-c57f-4f06-ac5e-ffd3466d13bb",
  "name" : "date_created",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "date",
  "formatters" : [ "uuuu-MM-dd" ]
},{
  "id" : "772d7440-52ce-4506-b6d7-4478ad591535",
  "name" : "date_retired",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "date",
  "formatters" : [ "uuuu-MM-dd" ]
},{
  "id" : "19b0adcf-5763-4254-821c-ab4c4a9561f8",
  "name" : "state_name",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "ba35881d-e60f-42c2-a73c-8ccd2f160e3a",
  "name" : "state_abbreviation",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
}]

=== AGLEnergy/arc/tutorial/gnaf/meta/0/locality_alias_type_aut.json
[{
  "id" : "30157d26-e628-40ef-922e-90c4c01e8445",
  "name" : "code",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "28a5b397-e1eb-47b1-b9bc-42459be636d9",
  "name" : "name",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "3aeef80e-c9b8-4070-a947-af176da5cbff",
  "name" : "description",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
}]
