=== AGLEnergy/arc/src/main/resources/metadata-schema.json
{
    "definitions": {},
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://example.com/example.json",
    "items": {
        "$id": "http://example.com/example.json/items",
        "type": "object",
        "properties": {
            "id": {
                "$id": "http://example.com/example.json/items/properties/id",
                "type": "string",
                "title": "id",
                "description": "Field unique identifier (GUID).",
                "default": "",
                "examples": [
                    "8275594c-6177-475e-b462-5f15d015df7c"
                ]
            },
            "name": {
                "$id": "http://example.com/example.json/items/properties/name",
                "type": "string",
                "title": "name",
                "description": "The name of the field.",
                "default": "",
                "examples": [
                    "first_name",
                    "last_name"
                ]
            },
            "description": {
                "$id": "http://example.com/example.json/items/properties/description",
                "type": "string",
                "title": "description",
                "description": "A description of the what the field represents.",
                "default": "",
                "examples": [
                    "Customer First Name",
                    "Timestamp of last customer interaction."
                ]
            },
            "nullReplacementValue": {
                "$id": "http://example.com/example.json/items/properties/nullReplacementValue",
                "type": "string",
                "title": "nullReplacementValue",
                "description": "The value to replace any nulls with.",
                "default": "",
                "examples": [
                    "true"
                ]
            },
            "trim": {
                "$id": "http://example.com/example.json/items/properties/trim",
                "type": "boolean",
                "title": "trim",
                "description": "Whether to trim this field before attempting data type conversion.",
                "default": false,
                "examples": [
                    true,
                    false
                ]
            },
            "nullable": {
                "$id": "http://example.com/example.json/items/properties/nullable",
                "type": "boolean",
                "title": "nullable",
                "description": "Whether this field is allowed to be null.",
                "default": false,
                "examples": [
                    true,
                    false
                ]
            },
            "nullableValues": {
                "$id": "http://example.com/example.json/items/properties/nullableValues",
                "type": "array",
                "title": "nullableValues",
                "description": "A list of values which will be treated as valid null values.",
                "examples": [
                    "NULL",
                    "null",
                    ""
                ],
                "items": {
                    "$id": "http://example.com/example.json/items/properties/nullableValues/items",
                    "type": "string",
                    "title": "The 0 Schema.",
                    "description": "An explanation about the purpose of this instance.",
                    "default": "",
                    "examples": [
                        ""
                    ]
                }
            },
            "primaryKey": {
                "$id": "http://example.com/example.json/items/properties/primaryKey",
                "type": "boolean",
                "title": "primaryKey",
                "description": "A flag to indicate if this is a primary key for metadata tracking/validation purposes.",
                "default": false,
                "examples": [
                    true,
                    false
                ]
            },
            "type": {
                "$id": "http://example.com/example.json/items/properties/type",
                "type": "string",
                "enum": [
                    "date",
                    "decimal",
                    "integer",
                    "string",
                    "timestamp",
                    "boolean"
                ],
                "title": "type",
                "description": "The data type of this field.",
                "default": "",
                "examples": [
                    "date",
                    "decimal",
                    "integer",
                    "string",
                    "timestamp"
                ]
            },
            "length": {
                "$id": "http://example.com/example.json/items/properties/length",
                "type": "integer",
                "title": "length",
                "description": "The length of the field for metadata tracking/validation purposes.",
                "examples": [
                    6,
                    255
                ]
            },
            "precision": {
                "$id": "http://example.com/example.json/items/properties/precision",
                "type": "integer",
                "title": "precision",
                "description": "Precision of Decimal field. For example, the number 1234.567 has a precision of seven.",
                "minimum": 1,
                "examples": [
                    7
                ]
            },
            "scale": {
                "$id": "http://example.com/example.json/items/properties/scale",
                "type": "integer",
                "title": "scale",
                "description": "Scale of Decimal field. For example, the number 1234.567 has a scale of three.",
                "minimum": 0,
                "examples": [
                    3
                ]
            },
            "timezoneId": {
                "$id": "http://example.com/example.json/items/properties/timezoneId",
                "type": "string",
                "title": "timezoneId",
                "description": "The timezone (offset) used to parse timestamp.",
                "examples": [
                    "+1000",
                    "AEST",
                    "Sydney/Australia"
                ]
            },
            "formatters": {
                "$id": "http://example.com/example.json/items/properties/formatters",
                "type": "array",
                "title": "formatters",
                "description": "A list of formatters to attempt to convert a string to a timestamp. Order by most frequent value descending.",
                "examples": [
                    "dd/MM/yyyy HH:mm:ss",
                    "dd/MM/yyyy H:mm:ss",
                    "dd/MM/yyyy HH:mm",
                    "dd/MM/yyyy H:mm",
                    "d/MM/yyyy HH:mm:ss",
                    "d/MM/yyyy H:mm:ss",
                    "d/MM/yyyy HH:mm",
                    "d/MM/yyyy H:mm"
                ]
            },
            "table": {
                "$id": "http://example.com/example.json/items/properties/table",
                "type": "string",
                "title": "table",
                "description": "A source table name used for metadata tracking/validation purposes.",
                "default": "",
                "examples": [
                    "customer_details",
                    "transactions"
                ]
            },
            "trueValues": {
                "$id": "http://example.com/example.json/items/properties/trueValues",
                "type": "array",
                "title": "trueValues",
                "description": "A list of values which are considered as true. Try to order this list so the values are arranged from most frequent to least frequent.",
                "examples": [
                    "true",
                    "T",
                    "1"
                ]
            },
            "falseValues": {
                "$id": "http://example.com/example.json/items/properties/falseValues",
                "type": "array",
                "title": "falseValues",
                "description": "A list of values which are considered as false. Try to order this list so the values are arranged from most frequent to least frequent.",
                "examples": [
                    "false",
                    "F",
                    "0"
                ]
            },
            "metadata": {
                "$id": "http://example.com/example.json/items/properties/metadata",
                "type": "object",
                "title": "metadata",
                "description": "Any metadata to attach to the column."
            }
        },
        "allOf": [
            {
                "if": {
                    "properties": {
                        "type": {
                            "enum": [
                                "integer",
                                "long",
                                "string"
                            ]
                        }
                    }
                },
                "then": {
                    "required": [
                        "id",
                        "name",
                        "trim",
                        "nullable",
                        "type",
                        "nullableValues"
                    ]
                }
            },
            {
                "if": {
                    "properties": {
                        "type": {
                            "enum": [
                                "decimal"
                            ]
                        }
                    }
                },
                "then": {
                    "required": [
                        "id",
                        "name",
                        "trim",
                        "nullable",
                        "type",
                        "nullableValues",
                        "precision",
                        "scale"
                    ]
                }
            },
            {
                "if": {
                    "properties": {
                        "type": {
                            "enum": [
                                "timestamp"
                            ]
                        }
                    }
                },
                "then": {
                    "required": [
                        "id",
                        "name",
                        "trim",
                        "nullable",
                        "type",
                        "nullableValues",
                        "timezoneId",
                        "formatters"
                    ]
                }
            },
            {
                "if": {
                    "properties": {
                        "type": {
                            "enum": [
                                "date"
                            ]
                        }
                    }
                },
                "then": {
                    "required": [
                        "id",
                        "name",
                        "trim",
                        "nullable",
                        "type",
                        "nullableValues",
                        "formatters"
                    ]
                }
            },
            {
                "if": {
                    "properties": {
                        "type": {
                            "enum": [
                                "time"
                            ]
                        }
                    }
                },
                "then": {
                    "required": [
                        "id",
                        "name",
                        "trim",
                        "nullable",
                        "type",
                        "nullableValues",
                        "formatters"
                    ]
                }
            },
            {
                "if": {
                    "properties": {
                        "type": {
                            "enum": [
                                "boolean"
                            ]
                        }
                    }
                },
                "then": {
                    "required": [
                        "id",
                        "name",
                        "trim",
                        "nullable",
                        "type",
                        "nullableValues",
                        "trueValues",
                        "falseValues"
                    ]
                }
            }
        ],
        "additionalProperties": false
    }
}

=== AGLEnergy/arc/tutorial/gnaf/meta/0/flat_type_aut.json
[{
  "id" : "02afa443-b688-4648-b813-7248e3536d9a",
  "name" : "code",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "59ad5ece-60ab-43fa-a985-e91a877e4a10",
  "name" : "name",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "ae81f2c6-8bcb-4763-bbcc-1206fadbd1bc",
  "name" : "description",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
}]

=== AGLEnergy/arc/tutorial/gnaf/meta/0/street_locality_alias_type_aut.json
[{
  "id" : "0cb9a535-598f-4a72-8947-583545f886d0",
  "name" : "code",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "9c5f366a-1efb-48a8-b89b-3586bae95e7e",
  "name" : "name",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "237bc4fc-3c7a-4726-be81-b6fca6d7a1d3",
  "name" : "description",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
}]

=== AGLEnergy/arc/tutorial/gnaf/meta/0/mb_2011.json
[{
  "id" : "7a634327-6a46-4860-ac78-3f3ce90e2e12",
  "name" : "mb_2011_pid",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "67157269-c3e9-4178-815f-311905fc9b14",
  "name" : "date_created",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "date",
  "formatters" : [ "uuuu-MM-dd" ]
},{
  "id" : "07532860-8c89-4de8-9928-a853f247af54",
  "name" : "date_retired",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "date",
  "formatters" : [ "uuuu-MM-dd" ]
},{
  "id" : "68bdb5c8-9dc2-4dc3-bb56-515790e58908",
  "name" : "mb_2011_code",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
}]

=== AGLEnergy/arc/tutorial/gnaf/meta/0/street_locality.json
[{
  "id" : "7a492291-f410-46a0-a266-eae183a0b96a",
  "name" : "street_locality_pid",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "515cda99-b9ac-44c9-a0ff-c7540dbc1165",
  "name" : "date_created",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "date",
  "formatters" : [ "uuuu-MM-dd" ]
},{
  "id" : "158c4f2e-10ac-491e-926e-f2e54562dcf7",
  "name" : "date_retired",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "date",
  "formatters" : [ "uuuu-MM-dd" ]
},{
  "id" : "326f7b72-9745-4d9e-98f1-c7788459546c",
  "name" : "street_class_code",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "c18ee707-17ce-4261-beee-83465147778d",
  "name" : "street_name",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "dbb0a980-fa00-43a7-8352-8792f049dbff",
  "name" : "street_type_code",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "65fd4f3e-6bbb-4ed6-a710-91288be6ad4d",
  "name" : "street_suffix_code",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "fed5a9cc-84b8-48ea-ad69-1540180894e5",
  "name" : "locality_pid",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "1555751a-a706-415e-a31d-d91f6e827340",
  "name" : "gnaf_street_pid",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "d6f858aa-1d19-4b5d-a28f-d076672c3c29",
  "name" : "gnaf_street_confidence",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "integer"
},{
  "id" : "9e731c91-8bbb-488a-8016-a5e502cad8a5",
  "name" : "gnaf_reliability_code",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "integer"
}]

=== AGLEnergy/arc/tutorial/gnaf/meta/0/address_change_type_aut.json
[{
  "id" : "879f300c-85d9-4ed1-90ee-f3f2766fce5c",
  "name" : "code",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "8f0be206-ffa6-4f9d-80ac-907cf8cd9b6e",
  "name" : "name",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "9a0ae361-5118-48cd-9611-a7be1d9224f1",
  "name" : "description",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
}]

=== AGLEnergy/arc/tutorial/gnaf/meta/0/address_alias.json
[{
  "id" : "ce669ee4-d65e-4988-b9d0-afd7eba77935",
  "name" : "address_alias_pid",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "04885441-7124-45ca-8873-9499f30c5e1a",
  "name" : "date_created",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "date",
  "formatters" : [ "yyyy-MM-dd" ]
},{
  "id" : "eb2c07c0-549e-4bcf-9437-232e266d3b89",
  "name" : "date_retired",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "date",
  "formatters" : [ "yyyy-MM-dd" ]
},{
  "id" : "8697079f-37d5-4e5a-851e-665c42b09575",
  "name" : "principal_pid",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "01967040-32eb-429e-ab9f-013acd5dc75f",
  "name" : "alias_pid",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "3c1d47b1-f9fc-45f3-94ec-49bbaf87f06e",
  "name" : "alias_type_code",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "f38319bf-b0b3-418c-a808-0a0bcf207177",
  "name" : "alias_comment",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
}]

=== AGLEnergy/arc/tutorial/gnaf/meta/0/address_feature.json
[{
  "id" : "047567eb-18f9-4a6a-b9d1-030f3ec545bd",
  "name" : "address_feature_id",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "467a4201-09fc-4a2b-9604-d4e8504d768d",
  "name" : "address_feature_pid",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "2c09e737-fd3a-454c-bd15-853d131d7190",
  "name" : "address_detail_pid",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "46c48e3a-2d97-46fe-a743-e6e9f5f173e8",
  "name" : "date_address_detail_created",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "date",
  "formatters" : [ "uuuu-MM-dd" ]
},{
  "id" : "0920791b-9c6e-45d4-b651-2e5a51fe27aa",
  "name" : "date_address_detail_retired",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "date",
  "formatters" : [ "uuuu-MM-dd" ]
},{
  "id" : "0b236f44-0cef-418f-920e-5c50d1b9f45c",
  "name" : "address_change_type_code",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
}]

=== AGLEnergy/arc/tutorial/gnaf/meta/0/geocoded_level_type_aut.json
[{
  "id" : "3f1dc3d0-2490-411a-b05c-8382a6a90f8a",
  "name" : "code",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "integer"
},{
  "id" : "6701454c-7f25-4e48-a1db-5edbdd5818a0",
  "name" : "name",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
},{
  "id" : "5245f1dc-ca81-4754-a9f1-403934f3ad0e",
  "name" : "description",
  "description" : "",
  "nullable" : true,
  "trim" : true,
  "nullableValues" : [ "", "null" ],
  "metadata" : { },
  "type" : "string"
}]
